Add vice presidents
csesoc/constitution pull request #57
Opened 2022-09-05 06:42 UTC by hayeselnut

2022-09-05 06:53 UTC, SpanishPear requested changes
see comments

2022-09-05 06:53 UTC, SpanishPear commented on CONSTITUTION.rst
> +   #. Supervise the external facing aspects of the society, especially the Careers and Events portfolios.
Careers and Events portfolios do/should not exist in the constitution

2022-09-05 06:53 UTC, SpanishPear commented on CONSTITUTION.rst
> +   #. Supervise the internal facing operations of the society, especially the Content and Development portfolios.
Content/Development portfolios do/should not exist in the constitution

E.g. - dev likely wont exist in '23

2022-09-08 04:01 UTC, hayeselnut commented
https://drive.google.com/file/d/1iXmM0ppUenm5CwZxacW2nKQPLqU9IMW2/view?fbclid=IwAR2lqduZ2pNdR0RI9VGfsCTcNBoEZpvvFbWMljXd0UV-NDyMauUkG08qYBY

2022-09-22 04:28 UTC, lting0804 commented
Clause 3.3.2. ii currently says at least 2 candidates for Co President and 1 for each other position

needs to be amended to say at least 2 for Vice President Development as well :)

2022-09-30 10:40 UTC, lting0804 commented
Approved at AGM

2022-09-30 10:41 UTC, merged